/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openai.api.v1.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.api.v1.client.ChatCompletionRequestUserMessageContentPart;

import java.util.ArrayList;
import java.util.List;
/**
 * Messages sent by an end user, containing prompts or additional context information. 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-24T09:41:34.975894600+07:00[Asia/Bangkok]")

public class ChatCompletionRequestUserMessage implements ChatCompletionRequestMessage, OneOfFineTuneChatRequestInputMessagesItems, OneOfFineTunePreferenceRequestInputInputMessagesItems {
  @JsonProperty("content")
  private List<ChatCompletionRequestUserMessageContentPart> content = new ArrayList<>();

  @JsonProperty("role")
  private String role = null;

  @JsonProperty("name")
  private String name = null;

  public ChatCompletionRequestUserMessage content(List<ChatCompletionRequestUserMessageContentPart> content) {
    this.content = content;
    return this;
  }

  public ChatCompletionRequestUserMessage addContentItem(ChatCompletionRequestUserMessageContentPart contentItem) {
    this.content.add(contentItem);
    return this;
  }

   /**
   * The contents of the user message. 
   * @return content
  **/
  public List<ChatCompletionRequestUserMessageContentPart> getContent() {
    return content;
  }

  public void setContent(List<ChatCompletionRequestUserMessageContentPart> content) {
    this.content = content;
  }

  public ChatCompletionRequestUserMessage role(String role) {
    this.role = role;
    return this;
  }

   /**
   * The role of the messages author, in this case &#x60;user&#x60;.
   * @return role
  **/
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public ChatCompletionRequestUserMessage name(String name) {
    this.name = name;
    return this;
  }

   /**
   * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionRequestUserMessage chatCompletionRequestUserMessage = (ChatCompletionRequestUserMessage) o;
    return Objects.equals(this.content, chatCompletionRequestUserMessage.content) &&
        Objects.equals(this.role, chatCompletionRequestUserMessage.role) &&
        Objects.equals(this.name, chatCompletionRequestUserMessage.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, role, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionRequestUserMessage {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
