/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openai.api.v1.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ChatCompletionRequestMessageContentPartRefusal
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-24T09:41:34.975894600+07:00[Asia/Bangkok]")

public class ChatCompletionRequestMessageContentPartRefusal implements ChatCompletionRequestAssistantMessageContentPart {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("refusal")
  private String refusal = null;

  public ChatCompletionRequestMessageContentPartRefusal type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the content part.
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ChatCompletionRequestMessageContentPartRefusal refusal(String refusal) {
    this.refusal = refusal;
    return this;
  }

   /**
   * The refusal message generated by the model.
   * @return refusal
  **/
  public String getRefusal() {
    return refusal;
  }

  public void setRefusal(String refusal) {
    this.refusal = refusal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionRequestMessageContentPartRefusal chatCompletionRequestMessageContentPartRefusal = (ChatCompletionRequestMessageContentPartRefusal) o;
    return Objects.equals(this.type, chatCompletionRequestMessageContentPartRefusal.type) &&
        Objects.equals(this.refusal, chatCompletionRequestMessageContentPartRefusal.refusal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, refusal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionRequestMessageContentPartRefusal {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    refusal: ").append(toIndentedString(refusal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
