/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openai.api.v1.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.api.v1.client.ChatCompletionMessageToolCalls;
import com.openai.api.v1.client.ChatCompletionResponseMessageAudio;
import com.openai.api.v1.client.ChatCompletionResponseMessageFunctionCall;

/**
 * A chat completion message generated by the model.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-24T09:41:34.975894600+07:00[Asia/Bangkok]")

public class ChatCompletionResponseMessage {
  @JsonProperty("content")
  private String content = null;

  @JsonProperty("refusal")
  private String refusal = null;

  @JsonProperty("tool_calls")
  private ChatCompletionMessageToolCalls toolCalls = null;

  /**
   * The role of the author of this message.
   */
  public enum RoleEnum {
    ASSISTANT("assistant");

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RoleEnum fromValue(String input) {
      for (RoleEnum b : RoleEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("role")
  private RoleEnum role = null;

  @JsonProperty("function_call")
  private ChatCompletionResponseMessageFunctionCall functionCall = null;

  @JsonProperty("audio")
  private ChatCompletionResponseMessageAudio audio = null;

  public ChatCompletionResponseMessage content(String content) {
    this.content = content;
    return this;
  }

   /**
   * The contents of the message.
   * @return content
  **/
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public ChatCompletionResponseMessage refusal(String refusal) {
    this.refusal = refusal;
    return this;
  }

   /**
   * The refusal message generated by the model.
   * @return refusal
  **/
  public String getRefusal() {
    return refusal;
  }

  public void setRefusal(String refusal) {
    this.refusal = refusal;
  }

  public ChatCompletionResponseMessage toolCalls(ChatCompletionMessageToolCalls toolCalls) {
    this.toolCalls = toolCalls;
    return this;
  }

   /**
   * Get toolCalls
   * @return toolCalls
  **/
  public ChatCompletionMessageToolCalls getToolCalls() {
    return toolCalls;
  }

  public void setToolCalls(ChatCompletionMessageToolCalls toolCalls) {
    this.toolCalls = toolCalls;
  }

  public ChatCompletionResponseMessage role(RoleEnum role) {
    this.role = role;
    return this;
  }

   /**
   * The role of the author of this message.
   * @return role
  **/
  public RoleEnum getRole() {
    return role;
  }

  public void setRole(RoleEnum role) {
    this.role = role;
  }

  public ChatCompletionResponseMessage functionCall(ChatCompletionResponseMessageFunctionCall functionCall) {
    this.functionCall = functionCall;
    return this;
  }

   /**
   * Get functionCall
   * @return functionCall
  **/
  public ChatCompletionResponseMessageFunctionCall getFunctionCall() {
    return functionCall;
  }

  public void setFunctionCall(ChatCompletionResponseMessageFunctionCall functionCall) {
    this.functionCall = functionCall;
  }

  public ChatCompletionResponseMessage audio(ChatCompletionResponseMessageAudio audio) {
    this.audio = audio;
    return this;
  }

   /**
   * Get audio
   * @return audio
  **/
  public ChatCompletionResponseMessageAudio getAudio() {
    return audio;
  }

  public void setAudio(ChatCompletionResponseMessageAudio audio) {
    this.audio = audio;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionResponseMessage chatCompletionResponseMessage = (ChatCompletionResponseMessage) o;
    return Objects.equals(this.content, chatCompletionResponseMessage.content) &&
        Objects.equals(this.refusal, chatCompletionResponseMessage.refusal) &&
        Objects.equals(this.toolCalls, chatCompletionResponseMessage.toolCalls) &&
        Objects.equals(this.role, chatCompletionResponseMessage.role) &&
        Objects.equals(this.functionCall, chatCompletionResponseMessage.functionCall) &&
        Objects.equals(this.audio, chatCompletionResponseMessage.audio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, refusal, toolCalls, role, functionCall, audio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionResponseMessage {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    refusal: ").append(toIndentedString(refusal)).append("\n");
    sb.append("    toolCalls: ").append(toIndentedString(toolCalls)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    functionCall: ").append(toIndentedString(functionCall)).append("\n");
    sb.append("    audio: ").append(toIndentedString(audio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
