/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openai.api.v1.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.api.v1.client.CreateModerationResponseCategories;
import com.openai.api.v1.client.CreateModerationResponseCategoryAppliedInputTypes;
import com.openai.api.v1.client.CreateModerationResponseCategoryScores;

/**
 * CreateModerationResponseResults
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-24T09:41:34.975894600+07:00[Asia/Bangkok]")

public class CreateModerationResponseResults {
  @JsonProperty("flagged")
  private Boolean flagged = null;

  @JsonProperty("categories")
  private CreateModerationResponseCategories categories = null;

  @JsonProperty("category_scores")
  private CreateModerationResponseCategoryScores categoryScores = null;

  @JsonProperty("category_applied_input_types")
  private CreateModerationResponseCategoryAppliedInputTypes categoryAppliedInputTypes = null;

  public CreateModerationResponseResults flagged(Boolean flagged) {
    this.flagged = flagged;
    return this;
  }

   /**
   * Whether any of the below categories are flagged.
   * @return flagged
  **/
  public Boolean isFlagged() {
    return flagged;
  }

  public void setFlagged(Boolean flagged) {
    this.flagged = flagged;
  }

  public CreateModerationResponseResults categories(CreateModerationResponseCategories categories) {
    this.categories = categories;
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  public CreateModerationResponseCategories getCategories() {
    return categories;
  }

  public void setCategories(CreateModerationResponseCategories categories) {
    this.categories = categories;
  }

  public CreateModerationResponseResults categoryScores(CreateModerationResponseCategoryScores categoryScores) {
    this.categoryScores = categoryScores;
    return this;
  }

   /**
   * Get categoryScores
   * @return categoryScores
  **/
  public CreateModerationResponseCategoryScores getCategoryScores() {
    return categoryScores;
  }

  public void setCategoryScores(CreateModerationResponseCategoryScores categoryScores) {
    this.categoryScores = categoryScores;
  }

  public CreateModerationResponseResults categoryAppliedInputTypes(CreateModerationResponseCategoryAppliedInputTypes categoryAppliedInputTypes) {
    this.categoryAppliedInputTypes = categoryAppliedInputTypes;
    return this;
  }

   /**
   * Get categoryAppliedInputTypes
   * @return categoryAppliedInputTypes
  **/
  public CreateModerationResponseCategoryAppliedInputTypes getCategoryAppliedInputTypes() {
    return categoryAppliedInputTypes;
  }

  public void setCategoryAppliedInputTypes(CreateModerationResponseCategoryAppliedInputTypes categoryAppliedInputTypes) {
    this.categoryAppliedInputTypes = categoryAppliedInputTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateModerationResponseResults createModerationResponseResults = (CreateModerationResponseResults) o;
    return Objects.equals(this.flagged, createModerationResponseResults.flagged) &&
        Objects.equals(this.categories, createModerationResponseResults.categories) &&
        Objects.equals(this.categoryScores, createModerationResponseResults.categoryScores) &&
        Objects.equals(this.categoryAppliedInputTypes, createModerationResponseResults.categoryAppliedInputTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flagged, categories, categoryScores, categoryAppliedInputTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateModerationResponseResults {\n");
    
    sb.append("    flagged: ").append(toIndentedString(flagged)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    categoryScores: ").append(toIndentedString(categoryScores)).append("\n");
    sb.append("    categoryAppliedInputTypes: ").append(toIndentedString(categoryAppliedInputTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
