/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openai.api.v1.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * A list of the categories along with the input type(s) that the score applies to.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-24T09:41:34.975894600+07:00[Asia/Bangkok]")

public class CreateModerationResponseCategoryAppliedInputTypes {
  /**
   * Gets or Sets hate
   */
  public enum HateEnum {
    TEXT("text");

    private String value;

    HateEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static HateEnum fromValue(String input) {
      for (HateEnum b : HateEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("hate")
  private List<HateEnum> hate = new ArrayList<>();

  /**
   * Gets or Sets hatethreatening
   */
  public enum HatethreateningEnum {
    TEXT("text");

    private String value;

    HatethreateningEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static HatethreateningEnum fromValue(String input) {
      for (HatethreateningEnum b : HatethreateningEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("hate/threatening")
  private List<HatethreateningEnum> hatethreatening = new ArrayList<>();

  /**
   * Gets or Sets harassment
   */
  public enum HarassmentEnum {
    TEXT("text");

    private String value;

    HarassmentEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static HarassmentEnum fromValue(String input) {
      for (HarassmentEnum b : HarassmentEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("harassment")
  private List<HarassmentEnum> harassment = new ArrayList<>();

  /**
   * Gets or Sets harassmentthreatening
   */
  public enum HarassmentthreateningEnum {
    TEXT("text");

    private String value;

    HarassmentthreateningEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static HarassmentthreateningEnum fromValue(String input) {
      for (HarassmentthreateningEnum b : HarassmentthreateningEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("harassment/threatening")
  private List<HarassmentthreateningEnum> harassmentthreatening = new ArrayList<>();

  /**
   * Gets or Sets illicit
   */
  public enum IllicitEnum {
    TEXT("text");

    private String value;

    IllicitEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static IllicitEnum fromValue(String input) {
      for (IllicitEnum b : IllicitEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("illicit")
  private List<IllicitEnum> illicit = new ArrayList<>();

  /**
   * Gets or Sets illicitviolent
   */
  public enum IllicitviolentEnum {
    TEXT("text");

    private String value;

    IllicitviolentEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static IllicitviolentEnum fromValue(String input) {
      for (IllicitviolentEnum b : IllicitviolentEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("illicit/violent")
  private List<IllicitviolentEnum> illicitviolent = new ArrayList<>();

  /**
   * Gets or Sets selfHarm
   */
  public enum SelfHarmEnum {
    TEXT("text"),
    IMAGE("image");

    private String value;

    SelfHarmEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SelfHarmEnum fromValue(String input) {
      for (SelfHarmEnum b : SelfHarmEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("self-harm")
  private List<SelfHarmEnum> selfHarm = new ArrayList<>();

  /**
   * Gets or Sets selfHarmintent
   */
  public enum SelfHarmintentEnum {
    TEXT("text"),
    IMAGE("image");

    private String value;

    SelfHarmintentEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SelfHarmintentEnum fromValue(String input) {
      for (SelfHarmintentEnum b : SelfHarmintentEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("self-harm/intent")
  private List<SelfHarmintentEnum> selfHarmintent = new ArrayList<>();

  /**
   * Gets or Sets selfHarminstructions
   */
  public enum SelfHarminstructionsEnum {
    TEXT("text"),
    IMAGE("image");

    private String value;

    SelfHarminstructionsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SelfHarminstructionsEnum fromValue(String input) {
      for (SelfHarminstructionsEnum b : SelfHarminstructionsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("self-harm/instructions")
  private List<SelfHarminstructionsEnum> selfHarminstructions = new ArrayList<>();

  /**
   * Gets or Sets sexual
   */
  public enum SexualEnum {
    TEXT("text"),
    IMAGE("image");

    private String value;

    SexualEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SexualEnum fromValue(String input) {
      for (SexualEnum b : SexualEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("sexual")
  private List<SexualEnum> sexual = new ArrayList<>();

  /**
   * Gets or Sets sexualminors
   */
  public enum SexualminorsEnum {
    TEXT("text");

    private String value;

    SexualminorsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SexualminorsEnum fromValue(String input) {
      for (SexualminorsEnum b : SexualminorsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("sexual/minors")
  private List<SexualminorsEnum> sexualminors = new ArrayList<>();

  /**
   * Gets or Sets violence
   */
  public enum ViolenceEnum {
    TEXT("text"),
    IMAGE("image");

    private String value;

    ViolenceEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ViolenceEnum fromValue(String input) {
      for (ViolenceEnum b : ViolenceEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("violence")
  private List<ViolenceEnum> violence = new ArrayList<>();

  /**
   * Gets or Sets violencegraphic
   */
  public enum ViolencegraphicEnum {
    TEXT("text"),
    IMAGE("image");

    private String value;

    ViolencegraphicEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ViolencegraphicEnum fromValue(String input) {
      for (ViolencegraphicEnum b : ViolencegraphicEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("violence/graphic")
  private List<ViolencegraphicEnum> violencegraphic = new ArrayList<>();

  public CreateModerationResponseCategoryAppliedInputTypes hate(List<HateEnum> hate) {
    this.hate = hate;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addHateItem(HateEnum hateItem) {
    this.hate.add(hateItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;hate&#x27;.
   * @return hate
  **/
  public List<HateEnum> getHate() {
    return hate;
  }

  public void setHate(List<HateEnum> hate) {
    this.hate = hate;
  }

  public CreateModerationResponseCategoryAppliedInputTypes hatethreatening(List<HatethreateningEnum> hatethreatening) {
    this.hatethreatening = hatethreatening;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addHatethreateningItem(HatethreateningEnum hatethreateningItem) {
    this.hatethreatening.add(hatethreateningItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;hate/threatening&#x27;.
   * @return hatethreatening
  **/
  public List<HatethreateningEnum> getHatethreatening() {
    return hatethreatening;
  }

  public void setHatethreatening(List<HatethreateningEnum> hatethreatening) {
    this.hatethreatening = hatethreatening;
  }

  public CreateModerationResponseCategoryAppliedInputTypes harassment(List<HarassmentEnum> harassment) {
    this.harassment = harassment;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addHarassmentItem(HarassmentEnum harassmentItem) {
    this.harassment.add(harassmentItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;harassment&#x27;.
   * @return harassment
  **/
  public List<HarassmentEnum> getHarassment() {
    return harassment;
  }

  public void setHarassment(List<HarassmentEnum> harassment) {
    this.harassment = harassment;
  }

  public CreateModerationResponseCategoryAppliedInputTypes harassmentthreatening(List<HarassmentthreateningEnum> harassmentthreatening) {
    this.harassmentthreatening = harassmentthreatening;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addHarassmentthreateningItem(HarassmentthreateningEnum harassmentthreateningItem) {
    this.harassmentthreatening.add(harassmentthreateningItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;harassment/threatening&#x27;.
   * @return harassmentthreatening
  **/
  public List<HarassmentthreateningEnum> getHarassmentthreatening() {
    return harassmentthreatening;
  }

  public void setHarassmentthreatening(List<HarassmentthreateningEnum> harassmentthreatening) {
    this.harassmentthreatening = harassmentthreatening;
  }

  public CreateModerationResponseCategoryAppliedInputTypes illicit(List<IllicitEnum> illicit) {
    this.illicit = illicit;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addIllicitItem(IllicitEnum illicitItem) {
    this.illicit.add(illicitItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;illicit&#x27;.
   * @return illicit
  **/
  public List<IllicitEnum> getIllicit() {
    return illicit;
  }

  public void setIllicit(List<IllicitEnum> illicit) {
    this.illicit = illicit;
  }

  public CreateModerationResponseCategoryAppliedInputTypes illicitviolent(List<IllicitviolentEnum> illicitviolent) {
    this.illicitviolent = illicitviolent;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addIllicitviolentItem(IllicitviolentEnum illicitviolentItem) {
    this.illicitviolent.add(illicitviolentItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;illicit/violent&#x27;.
   * @return illicitviolent
  **/
  public List<IllicitviolentEnum> getIllicitviolent() {
    return illicitviolent;
  }

  public void setIllicitviolent(List<IllicitviolentEnum> illicitviolent) {
    this.illicitviolent = illicitviolent;
  }

  public CreateModerationResponseCategoryAppliedInputTypes selfHarm(List<SelfHarmEnum> selfHarm) {
    this.selfHarm = selfHarm;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addSelfHarmItem(SelfHarmEnum selfHarmItem) {
    this.selfHarm.add(selfHarmItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;self-harm&#x27;.
   * @return selfHarm
  **/
  public List<SelfHarmEnum> getSelfHarm() {
    return selfHarm;
  }

  public void setSelfHarm(List<SelfHarmEnum> selfHarm) {
    this.selfHarm = selfHarm;
  }

  public CreateModerationResponseCategoryAppliedInputTypes selfHarmintent(List<SelfHarmintentEnum> selfHarmintent) {
    this.selfHarmintent = selfHarmintent;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addSelfHarmintentItem(SelfHarmintentEnum selfHarmintentItem) {
    this.selfHarmintent.add(selfHarmintentItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;self-harm/intent&#x27;.
   * @return selfHarmintent
  **/
  public List<SelfHarmintentEnum> getSelfHarmintent() {
    return selfHarmintent;
  }

  public void setSelfHarmintent(List<SelfHarmintentEnum> selfHarmintent) {
    this.selfHarmintent = selfHarmintent;
  }

  public CreateModerationResponseCategoryAppliedInputTypes selfHarminstructions(List<SelfHarminstructionsEnum> selfHarminstructions) {
    this.selfHarminstructions = selfHarminstructions;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addSelfHarminstructionsItem(SelfHarminstructionsEnum selfHarminstructionsItem) {
    this.selfHarminstructions.add(selfHarminstructionsItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;self-harm/instructions&#x27;.
   * @return selfHarminstructions
  **/
  public List<SelfHarminstructionsEnum> getSelfHarminstructions() {
    return selfHarminstructions;
  }

  public void setSelfHarminstructions(List<SelfHarminstructionsEnum> selfHarminstructions) {
    this.selfHarminstructions = selfHarminstructions;
  }

  public CreateModerationResponseCategoryAppliedInputTypes sexual(List<SexualEnum> sexual) {
    this.sexual = sexual;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addSexualItem(SexualEnum sexualItem) {
    this.sexual.add(sexualItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;sexual&#x27;.
   * @return sexual
  **/
  public List<SexualEnum> getSexual() {
    return sexual;
  }

  public void setSexual(List<SexualEnum> sexual) {
    this.sexual = sexual;
  }

  public CreateModerationResponseCategoryAppliedInputTypes sexualminors(List<SexualminorsEnum> sexualminors) {
    this.sexualminors = sexualminors;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addSexualminorsItem(SexualminorsEnum sexualminorsItem) {
    this.sexualminors.add(sexualminorsItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;sexual/minors&#x27;.
   * @return sexualminors
  **/
  public List<SexualminorsEnum> getSexualminors() {
    return sexualminors;
  }

  public void setSexualminors(List<SexualminorsEnum> sexualminors) {
    this.sexualminors = sexualminors;
  }

  public CreateModerationResponseCategoryAppliedInputTypes violence(List<ViolenceEnum> violence) {
    this.violence = violence;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addViolenceItem(ViolenceEnum violenceItem) {
    this.violence.add(violenceItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;violence&#x27;.
   * @return violence
  **/
  public List<ViolenceEnum> getViolence() {
    return violence;
  }

  public void setViolence(List<ViolenceEnum> violence) {
    this.violence = violence;
  }

  public CreateModerationResponseCategoryAppliedInputTypes violencegraphic(List<ViolencegraphicEnum> violencegraphic) {
    this.violencegraphic = violencegraphic;
    return this;
  }

  public CreateModerationResponseCategoryAppliedInputTypes addViolencegraphicItem(ViolencegraphicEnum violencegraphicItem) {
    this.violencegraphic.add(violencegraphicItem);
    return this;
  }

   /**
   * The applied input type(s) for the category &#x27;violence/graphic&#x27;.
   * @return violencegraphic
  **/
  public List<ViolencegraphicEnum> getViolencegraphic() {
    return violencegraphic;
  }

  public void setViolencegraphic(List<ViolencegraphicEnum> violencegraphic) {
    this.violencegraphic = violencegraphic;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateModerationResponseCategoryAppliedInputTypes createModerationResponseCategoryAppliedInputTypes = (CreateModerationResponseCategoryAppliedInputTypes) o;
    return Objects.equals(this.hate, createModerationResponseCategoryAppliedInputTypes.hate) &&
        Objects.equals(this.hatethreatening, createModerationResponseCategoryAppliedInputTypes.hatethreatening) &&
        Objects.equals(this.harassment, createModerationResponseCategoryAppliedInputTypes.harassment) &&
        Objects.equals(this.harassmentthreatening, createModerationResponseCategoryAppliedInputTypes.harassmentthreatening) &&
        Objects.equals(this.illicit, createModerationResponseCategoryAppliedInputTypes.illicit) &&
        Objects.equals(this.illicitviolent, createModerationResponseCategoryAppliedInputTypes.illicitviolent) &&
        Objects.equals(this.selfHarm, createModerationResponseCategoryAppliedInputTypes.selfHarm) &&
        Objects.equals(this.selfHarmintent, createModerationResponseCategoryAppliedInputTypes.selfHarmintent) &&
        Objects.equals(this.selfHarminstructions, createModerationResponseCategoryAppliedInputTypes.selfHarminstructions) &&
        Objects.equals(this.sexual, createModerationResponseCategoryAppliedInputTypes.sexual) &&
        Objects.equals(this.sexualminors, createModerationResponseCategoryAppliedInputTypes.sexualminors) &&
        Objects.equals(this.violence, createModerationResponseCategoryAppliedInputTypes.violence) &&
        Objects.equals(this.violencegraphic, createModerationResponseCategoryAppliedInputTypes.violencegraphic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hate, hatethreatening, harassment, harassmentthreatening, illicit, illicitviolent, selfHarm, selfHarmintent, selfHarminstructions, sexual, sexualminors, violence, violencegraphic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateModerationResponseCategoryAppliedInputTypes {\n");
    
    sb.append("    hate: ").append(toIndentedString(hate)).append("\n");
    sb.append("    hatethreatening: ").append(toIndentedString(hatethreatening)).append("\n");
    sb.append("    harassment: ").append(toIndentedString(harassment)).append("\n");
    sb.append("    harassmentthreatening: ").append(toIndentedString(harassmentthreatening)).append("\n");
    sb.append("    illicit: ").append(toIndentedString(illicit)).append("\n");
    sb.append("    illicitviolent: ").append(toIndentedString(illicitviolent)).append("\n");
    sb.append("    selfHarm: ").append(toIndentedString(selfHarm)).append("\n");
    sb.append("    selfHarmintent: ").append(toIndentedString(selfHarmintent)).append("\n");
    sb.append("    selfHarminstructions: ").append(toIndentedString(selfHarminstructions)).append("\n");
    sb.append("    sexual: ").append(toIndentedString(sexual)).append("\n");
    sb.append("    sexualminors: ").append(toIndentedString(sexualminors)).append("\n");
    sb.append("    violence: ").append(toIndentedString(violence)).append("\n");
    sb.append("    violencegraphic: ").append(toIndentedString(violencegraphic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
