/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openai.api.v1.client;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
/**
* InlineResponse2001
*/
@JsonTypeInfo(
  use = JsonTypeInfo.Id.NAME,
  include = JsonTypeInfo.As.PROPERTY,
  property = "")
@JsonSubTypes({
  @JsonSubTypes.Type(value = CreateTranslationResponseJson.class, name = "CreateTranslationResponseJson"),
  @JsonSubTypes.Type(value = CreateTranslationResponseVerboseJson.class, name = "CreateTranslationResponseVerboseJson")
})
public interface InlineResponse2001 {

}
