/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openai.api.v1.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openai.api.v1.client.AssistantSupportedModels;
import com.openai.api.v1.client.AssistantTool;
import com.openai.api.v1.client.Metadata;
import com.openai.api.v1.client.ModifyAssistantRequestToolResources;
import com.openai.api.v1.client.ReasoningEffort;
import com.openai.api.v1.client.ResponseFormatOption;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * ModifyAssistantRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-24T09:41:34.975894600+07:00[Asia/Bangkok]")

public class ModifyAssistantRequest {
  @JsonProperty("model")
  private AssistantSupportedModels model = null;

  @JsonProperty("reasoning_effort")
  private ReasoningEffort reasoningEffort = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("instructions")
  private String instructions = null;

  @JsonProperty("tools")
  private List<AssistantTool> tools = null;

  @JsonProperty("tool_resources")
  private ModifyAssistantRequestToolResources toolResources = null;

  @JsonProperty("metadata")
  private Metadata metadata = null;

  @JsonProperty("temperature")
  private BigDecimal temperature = new BigDecimal(1);

  @JsonProperty("top_p")
  private BigDecimal topP = new BigDecimal(1);

  @JsonProperty("response_format")
  private ResponseFormatOption responseFormat = null;

  public ModifyAssistantRequest model(AssistantSupportedModels model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  public AssistantSupportedModels getModel() {
    return model;
  }

  public void setModel(AssistantSupportedModels model) {
    this.model = model;
  }

  public ModifyAssistantRequest reasoningEffort(ReasoningEffort reasoningEffort) {
    this.reasoningEffort = reasoningEffort;
    return this;
  }

   /**
   * Get reasoningEffort
   * @return reasoningEffort
  **/
  public ReasoningEffort getReasoningEffort() {
    return reasoningEffort;
  }

  public void setReasoningEffort(ReasoningEffort reasoningEffort) {
    this.reasoningEffort = reasoningEffort;
  }

  public ModifyAssistantRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the assistant. The maximum length is 256 characters. 
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ModifyAssistantRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the assistant. The maximum length is 512 characters. 
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ModifyAssistantRequest instructions(String instructions) {
    this.instructions = instructions;
    return this;
  }

   /**
   * The system instructions that the assistant uses. The maximum length is 256,000 characters. 
   * @return instructions
  **/
  public String getInstructions() {
    return instructions;
  }

  public void setInstructions(String instructions) {
    this.instructions = instructions;
  }

  public ModifyAssistantRequest tools(List<AssistantTool> tools) {
    this.tools = tools;
    return this;
  }

  public ModifyAssistantRequest addToolsItem(AssistantTool toolsItem) {
    if (this.tools == null) {
      this.tools = new ArrayList<>();
    }
    this.tools.add(toolsItem);
    return this;
  }

   /**
   * A list of tool enabled on the assistant. There can be a maximum of 128 tools per assistant. Tools can be of types &#x60;code_interpreter&#x60;, &#x60;file_search&#x60;, or &#x60;function&#x60;. 
   * @return tools
  **/
  public List<AssistantTool> getTools() {
    return tools;
  }

  public void setTools(List<AssistantTool> tools) {
    this.tools = tools;
  }

  public ModifyAssistantRequest toolResources(ModifyAssistantRequestToolResources toolResources) {
    this.toolResources = toolResources;
    return this;
  }

   /**
   * Get toolResources
   * @return toolResources
  **/
  public ModifyAssistantRequestToolResources getToolResources() {
    return toolResources;
  }

  public void setToolResources(ModifyAssistantRequestToolResources toolResources) {
    this.toolResources = toolResources;
  }

  public ModifyAssistantRequest metadata(Metadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  public Metadata getMetadata() {
    return metadata;
  }

  public void setMetadata(Metadata metadata) {
    this.metadata = metadata;
  }

  public ModifyAssistantRequest temperature(BigDecimal temperature) {
    this.temperature = temperature;
    return this;
  }

   /**
   * What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. 
   * minimum: 0
   * maximum: 2
   * @return temperature
  **/
  public BigDecimal getTemperature() {
    return temperature;
  }

  public void setTemperature(BigDecimal temperature) {
    this.temperature = temperature;
  }

  public ModifyAssistantRequest topP(BigDecimal topP) {
    this.topP = topP;
    return this;
  }

   /**
   * An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.  We generally recommend altering this or temperature but not both. 
   * minimum: 0
   * maximum: 1
   * @return topP
  **/
  public BigDecimal getTopP() {
    return topP;
  }

  public void setTopP(BigDecimal topP) {
    this.topP = topP;
  }

  public ModifyAssistantRequest responseFormat(ResponseFormatOption responseFormat) {
    this.responseFormat = responseFormat;
    return this;
  }

   /**
   * Get responseFormat
   * @return responseFormat
  **/
  public ResponseFormatOption getResponseFormat() {
    return responseFormat;
  }

  public void setResponseFormat(ResponseFormatOption responseFormat) {
    this.responseFormat = responseFormat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyAssistantRequest modifyAssistantRequest = (ModifyAssistantRequest) o;
    return Objects.equals(this.model, modifyAssistantRequest.model) &&
        Objects.equals(this.reasoningEffort, modifyAssistantRequest.reasoningEffort) &&
        Objects.equals(this.name, modifyAssistantRequest.name) &&
        Objects.equals(this.description, modifyAssistantRequest.description) &&
        Objects.equals(this.instructions, modifyAssistantRequest.instructions) &&
        Objects.equals(this.tools, modifyAssistantRequest.tools) &&
        Objects.equals(this.toolResources, modifyAssistantRequest.toolResources) &&
        Objects.equals(this.metadata, modifyAssistantRequest.metadata) &&
        Objects.equals(this.temperature, modifyAssistantRequest.temperature) &&
        Objects.equals(this.topP, modifyAssistantRequest.topP) &&
        Objects.equals(this.responseFormat, modifyAssistantRequest.responseFormat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(model, reasoningEffort, name, description, instructions, tools, toolResources, metadata, temperature, topP, responseFormat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyAssistantRequest {\n");
    
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    reasoningEffort: ").append(toIndentedString(reasoningEffort)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    instructions: ").append(toIndentedString(instructions)).append("\n");
    sb.append("    tools: ").append(toIndentedString(tools)).append("\n");
    sb.append("    toolResources: ").append(toIndentedString(toolResources)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    topP: ").append(toIndentedString(topP)).append("\n");
    sb.append("    responseFormat: ").append(toIndentedString(responseFormat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
