/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openai.api.v1.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RealtimeConversationItemContent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-24T09:41:34.975894600+07:00[Asia/Bangkok]")

public class RealtimeConversationItemContent {
  /**
   * The content type (&#x60;input_text&#x60;, &#x60;input_audio&#x60;, &#x60;item_reference&#x60;, &#x60;text&#x60;). 
   */
  public enum TypeEnum {
    INPUT_AUDIO("input_audio"),
    INPUT_TEXT("input_text"),
    ITEM_REFERENCE("item_reference"),
    TEXT("text");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("audio")
  private String audio = null;

  @JsonProperty("transcript")
  private String transcript = null;

  public RealtimeConversationItemContent type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The content type (&#x60;input_text&#x60;, &#x60;input_audio&#x60;, &#x60;item_reference&#x60;, &#x60;text&#x60;). 
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public RealtimeConversationItemContent text(String text) {
    this.text = text;
    return this;
  }

   /**
   * The text content, used for &#x60;input_text&#x60; and &#x60;text&#x60; content types. 
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public RealtimeConversationItemContent id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of a previous conversation item to reference (for &#x60;item_reference&#x60; content types in &#x60;response.create&#x60; events). These can reference both client and server created items. 
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RealtimeConversationItemContent audio(String audio) {
    this.audio = audio;
    return this;
  }

   /**
   * Base64-encoded audio bytes, used for &#x60;input_audio&#x60; content type. 
   * @return audio
  **/
  public String getAudio() {
    return audio;
  }

  public void setAudio(String audio) {
    this.audio = audio;
  }

  public RealtimeConversationItemContent transcript(String transcript) {
    this.transcript = transcript;
    return this;
  }

   /**
   * The transcript of the audio, used for &#x60;input_audio&#x60; content type. 
   * @return transcript
  **/
  public String getTranscript() {
    return transcript;
  }

  public void setTranscript(String transcript) {
    this.transcript = transcript;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RealtimeConversationItemContent realtimeConversationItemContent = (RealtimeConversationItemContent) o;
    return Objects.equals(this.type, realtimeConversationItemContent.type) &&
        Objects.equals(this.text, realtimeConversationItemContent.text) &&
        Objects.equals(this.id, realtimeConversationItemContent.id) &&
        Objects.equals(this.audio, realtimeConversationItemContent.audio) &&
        Objects.equals(this.transcript, realtimeConversationItemContent.transcript);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, text, id, audio, transcript);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RealtimeConversationItemContent {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    audio: ").append(toIndentedString(audio)).append("\n");
    sb.append("    transcript: ").append(toIndentedString(transcript)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
