# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.1.0/variables.json
Variables:
  llm:
    openai:
      # your openAI key/bearer token
      #[password]
      apiKey: ${decrypt:}
