name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v5
    with:
      mvnArgs: -U -Divy.release=nightly
    secrets:
      mvnArgs: -Dopenai.key=${{secrets.OPENAI_KEY}}