name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v6
    with:
      mvnArgs: -U -Divy.release=nightly